"""SQLAlchemy ORM models — the single authoritative schema definition.

Import rule: this module is imported EXCLUSIVELY by app/repositories/.
Routes, services, and domain modules must never import from here.
"""

import enum
from datetime import datetime

from fastapi_users.db import SQLAlchemyBaseUserTable
from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""


class BatchStatus(enum.StrEnum):
    """Lifecycle states of a document classification batch."""

    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"


class User(SQLAlchemyBaseUserTable[int], Base):
    """Registered application user.

    This model inherits the standard fastapi-users fields:

    - email
    - hashed_password
    - is_active
    - is_superuser
    - is_verified

    We define only the fields that are specific to our project:

    - id because we are using integer user IDs
    - role for our RBAC/Casbin permission story
    - created_at for auditability
    - relationships to batches and audit logs
    """

    __tablename__ = "users"

    # fastapi-users generic table needs us to define the integer primary key.
    id: Mapped[int] = mapped_column(primary_key=True)

    # Project-level RBAC role. New users default to auditor.
    # Admins can later promote users through the audited role-toggle endpoint.
    role: Mapped[str] = mapped_column(default="auditor")

    # SQLAlchemy Mapped[] uses the Python datetime type.
    # DateTime defines the actual database column type.
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    batches: Mapped[list["Batch"]] = relationship(back_populates="owner")
    audit_entries: Mapped[list["AuditLog"]] = relationship(back_populates="actor")


class Batch(Base):
    """A batch of one or more documents submitted for classification."""

    __tablename__ = "batches"

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    status: Mapped[BatchStatus] = mapped_column(default=BatchStatus.pending)

    # Creation timestamp for the batch.
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    # Updated automatically when SQLAlchemy changes the row.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
    )

    owner: Mapped["User"] = relationship(back_populates="batches")
    predictions: Mapped[list["Prediction"]] = relationship(back_populates="batch")


class Prediction(Base):
    """A single document's classification result within a batch."""

    __tablename__ = "predictions"

    id: Mapped[int] = mapped_column(primary_key=True)
    batch_id: Mapped[int] = mapped_column(ForeignKey("batches.id"), index=True)
    filename: Mapped[str]

    # MinIO object key for the original uploaded document.
    storage_key: Mapped[str]

    # MinIO object key for the annotated PNG generated by the inference worker.
    overlay_key: Mapped[str | None]

    predicted_label: Mapped[str]
    confidence: Mapped[float]

    # Stored as JSON array strings to keep the schema simple for Week 6.
    top5_labels: Mapped[str]
    top5_scores: Mapped[str]

    is_relabeled: Mapped[bool] = mapped_column(default=False)
    relabeled_to: Mapped[str | None]
    relabeled_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))

    # Timestamp for when the prediction row was created.
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    batch: Mapped["Batch"] = relationship(back_populates="predictions")


class AuditLog(Base):
    """Immutable record of every auditable event.

    Required audit events:
    - role changes
    - prediction relabels
    - batch status changes
    """

    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    actor_id: Mapped[int] = mapped_column(ForeignKey("users.id"))

    # Examples: "role_change", "relabel", "batch_state_change".
    action: Mapped[str]

    # Human-readable description of what changed.
    target: Mapped[str]

    # JSON extra context. Named metadata_ because SQLAlchemy reserves metadata.
    metadata_: Mapped[str | None]

    # Timestamp for when the audit event happened.
    timestamp: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    actor: Mapped["User"] = relationship(back_populates="audit_entries")


class CasbinRule(Base):
    """Casbin policy rule managed by casbin-sqlalchemy-adapter."""

    __tablename__ = "casbin_rule"

    id: Mapped[int] = mapped_column(primary_key=True)
    ptype: Mapped[str | None]
    v0: Mapped[str | None]
    v1: Mapped[str | None]
    v2: Mapped[str | None]
    v3: Mapped[str | None]
    v4: Mapped[str | None]
    v5: Mapped[str | None]